#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# global settings
yabai -m config                                 \
    external_bar                 all:27:0       \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        focused        \
    window_placement             second_child   \
    window_topmost               on             \
    window_shadow                float          \
                                                \
    insert_feedback_color        0xff9dd274     \
    active_window_border_color   0xffe1e3e4     \
    normal_window_border_color   0x002E3440     \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                on             \
    window_border_radious         6             \
    window_border_width           2             \
                                                \
    top_padding                  10             \
    bottom_padding                4             \
    left_padding                  4             \
    right_padding                 4             \
    window_gap                    4             \
                                                \
    mouse_modifier               ctrl           \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    window_topmost               off

yabai -m config layout bsp

yabai -m config --space 4 layout float
yabai -m config --space 5 layout float
yabai -m config --space 6 layout float

yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

echo "yabai configuration loaded.."

